name: Run Murder Scraper

on:
  workflow_dispatch:
    inputs:
      START:
        description: "Start number (e.g. 0)"
        required: true
        default: "0"
      END:
        description: "End number (e.g. 100)"
        required: true
        default: "100"
      YEAR:
        description: "Year (e.g. 2024)"
        required: true
        default: "2024"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        env:
          START: ${{ github.event.inputs.START }}
          END: ${{ github.event.inputs.END }}
          YEAR: ${{ github.event.inputs.YEAR }}
        run: python fetch.py
